### ISSUE TITLE
 genPartialSteerVector(theta, N, d, lambda, flag)

### ISSUE THREAD

**Issue by Inspirational-boy** [LiZhuoRan0/CRLB-demo#1]
在 genPartialSteerVector(theta, N, d, lambda, flag)函数中，这个导向矢量表示什么意思呢a = (1j*pi.*n*cos(asin(theta))).*exp(1j*2*pi*d*theta/lambda*n);

**Comment by LiZhuoRan0** [comment]
导向矢量对角度求导数得到的结果

**Comment by Inspirational-boy** [comment]
> 导向矢量对角度求导数得到的结果

谢谢大佬，看懂了
